spring.application.name=sistema_ventas_api
server.port=8080
logging.pattern.dateformat=hh:mm

# Conexión a la BD
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# Dialecto para MariaDB
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION}

## CORS
cors.allowed-origin=${FRONTEND_URL}